
[types]

	[types.wood_type]

		[types.wood_type.ars_nouveau]
			archwood = true

		[types.wood_type.quark]
			bamboo = true
			azalea = true
			blossom = true
			ancient = true

		[types.wood_type.botania]
			livingwood = true
			dreamwood = true

		[types.wood_type.biomesoplenty]
			fir = true
			redwood = true
			cherry = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true

		[types.wood_type.integrateddynamics]
			menril = true

		[types.wood_type.solarcraft]
			runic = true
			radiant = true

		[types.wood_type.evilcraft]
			undead = true

		[types.wood_type.twilightforest]
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.wood_type.forcecraft]
			force = true

		[types.wood_type.forbidden_arcanus]
			fungyss = true
			cherry = true
			aurum = true
			edelwood = true

		[types.wood_type.naturesaura]
			ancient = true

		[types.wood_type.hexerei]
			mahogany = true
			willow = true
			witch_hazel = true

	[types.leaves_type]

		[types.leaves_type.ars_nouveau]
			blue_archwood = true
			green_archwood = true
			purple_archwood = true
			red_archwood = true

		[types.leaves_type.biomesoplenty]
			origin = true
			flowering_oak = true
			maple = true
			orange_autumn = true
			yellow_autumn = true
			rainbow_birch = true
			fir = true
			redwood = true
			white_cherry = true
			pink_cherry = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true

		[types.leaves_type.integrateddynamics]
			menril = true

		[types.leaves_type.quark]
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			pink_blossom = true
			yellow_blossom = true
			red_blossom = true
			ancient = true

		[types.leaves_type.mythicbotany]
			dreamwood = true

		[types.leaves_type.ars_elemental]
			yellow_archwood = true

		[types.leaves_type.solarcraft]
			ash = true
			runic = true
			radiant = true

		[types.leaves_type.evilcraft]
			undead = true

		[types.leaves_type.ic2]
			rubber = true

		[types.leaves_type.twilightforest]
			beanstalk = true
			thorn = true
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			rainbow_oak = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.leaves_type.forcecraft]
			force = true

		[types.leaves_type.forbidden_arcanus]
			cherry = true
			aurum = true
			nuggety_aurum = true

		[types.leaves_type.naturesaura]
			ancient = true
			golden = true

		[types.leaves_type.occultism]
			otherworld = true

		[types.leaves_type.hexerei]
			mahogany = true
			willow = true
			witch_hazel = true

[entries]

	[entries.wood_type]

		[entries.wood_type.storagedrawers]
			full_drawers_2 = true
			half_drawers_1 = true
			full_drawers_4 = true
			half_drawers_4 = true
			trim = true
			half_drawers_2 = true
			full_drawers_1 = true

		[entries.wood_type.quark]
			vertical_planks = true
			post = true
			trapped_chest = true
			bookshelf = true
			chest = true
			stripped_post = true
			ladder = true
			hollow_log = true

		[entries.wood_type.create]
			window = true
			window_pane = true

		[entries.wood_type.twilightforest]
			hollow_log_horizontal = true
			hollow_log_vertical = true
			banister = true
			hollow_log_climbable = true

		[entries.wood_type.chipped]
			fine_planks = true
			polished_planks = true
			diagonal_planks = true
			framed_planks = true
			pegged_planks = true
			nailed_planks = true
			cornered_planks = true
			detailed_planks = true
			basket_woven_planks = true
			enclosed_planks = true
			hewn_planks = true
			crossed_planks = true
			double_herringbone_planks = true
			crated_planks = true
			planks_shavings = true
			fine_vertical_planks = true
			cross_laced_planks = true
			natural_planks = true
			planks_mosaic = true
			brick_bond_planks = true
			diamond_planks = true
			herringbone_planks = true
			laced_planks = true
			boxed_planks = true
			planks_panel = true
			bricky_planks = true

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

