
#General Settings
[general]
	#Clay, Glowstone, Quartz, Redstone and Snow Generators will generate dust items, not blocks.
	generate_dust = true
	#Enable the Ore Generator.
	oreGeneratorEnable = true
	#Enable the Dye Generator.
	dyeGeneratorEnable = true

#OreGenerator Probabilities
[oregenerator]
	#Comma separated list of the items and probabilities (probability value between 0.00 and 1.00) to be used in the Ore Generator, format to use: "modid:itemname*probability" e.g. "minecraft:iron_ore*0.45"
	oreGeneratorItems = ["minecraft:coal_ore*0.50", "thermal:tin_ore*0.40", "minecraft:iron_ore*0.45", "minecraft:gold_ore*0.25", "minecraft:lapis_ore*0.10", "minecraft:redstone_ore*0.10", "minecraft:diamond_ore*0.05", "minecraft:emerald_ore*0.02", "minecraft:nether_quartz_ore*0.00", "minecraft:ancient_debris*0.01", "minecraft:copper_ore*0.40"]

#Generator Settings
[gensettings]

	#Tier: 1
	[gensettings.1]
		#Ticks between every generation update.
		#Range: > 1
		interval = 500

	#Tier: 2
	[gensettings.2]
		#Ticks between every generation update.
		#Range: > 1
		interval = 400

	#Tier: 3
	[gensettings.3]
		#Ticks between every generation update.
		#Range: > 1
		interval = 300

	#Tier: 4
	[gensettings.4]
		#Ticks between every generation update.
		#Range: > 1
		interval = 200

	#Tier: 5
	[gensettings.5]
		#Ticks between every generation update.
		#Range: > 1
		interval = 60

