
["Configs For Universutil"]
	#What Dimension To Go To (Starting from Overworld)
	"Dimension Name 1" = "minecraft:overworld"
	#Y Value From Where You Want The TP To Happen
	#Range: -64 ~ 256
	"Y Value" = -63
	#What Dimension To Go To
	"Dimension Name 2" = "minecraft:the_nether"
	#Y Value From Where You Want The TP To Happen
	#Range: -64 ~ 256
	"Y Value 2" = 1

